# Grapefruit OS — Calamares users module
---
defaultGroups:
    - sudo
    - audio
    - video
    - plugdev
    - netdev

doAutologin:            false
doReusePassword:        true
setRootPassword:        false
avoidOverlap:           true

passwordRequirements:
    minLength:          8
    maxLength:          0
