# Grapefruit OS — Calamares welcome module
---
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    true

requirements:
    requiredStorage:    8.0
    requiredRam:        2.0
    internetCheckUrl:   https://github.com/djlacavera21/Grapefruit-OS
    check:
        - storage
        - ram
        - power
        - root
    required:
        - storage
        - ram
        - root
